<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_BigBagActualMassStore" Id="{cdb68e65-853a-41ec-96c7-de00162eaa0c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BigBagActualMassStore
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_BigBagActualMassStore">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>